services:
  - type: web
    name: industrial-project-registry
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false # Set this in the Render dashboard
      - key: PYTHON_VERSION
        value: 3.10.0
